.travis.yml
Runs travis tests in nodejs v0.10, v0.12, and iojs.
=> Test in more nodes

languages/sv-SE.js, numbro.js, tests/languages/sv-SE.js
=> Fixes Swedish tests

package.json, tests/languages/locale-codes.js
Tests for the format of locale codes used in numbro languages.
=> Tests for culture code format

languages.html
You should place links titled »Edit this page« within the docs. This makes it easier to create pull requests :kissing_heart: 
See [Yeoman Docs](http://yeoman.io/authoring/running-context.html) for example.
=> Replace reference to `numeral` with `numbro`

numbro.js
https://github.com/foretagsplatsen/numbro/issues/64
=> Fix for multiply losing accuracy on minification

numbro.js, tests/languages/all.js
=> Load all languages automatically when running under Node.JS

format.html, manipulate.html
Converted `numeral` references to `numbro` where appropriate. Resolves #75
=> Resolves #75

numbro.js, package.json
=> Allow loading of cultures in node explicitly if numbro hasn't detected correctly that it is in node

languages.html
It should say `can't`, not `can` 😄
=> fix spelling in languages page

numbro.js, tests/numbro/format.js
refer https://github.com/foretagsplatsen/numbro/pull/172 for full discussion
The rebase I tried did something weird, branched off latest develop and `cherry-pick`ed commits.
(turns out I had forgotten the `--force` flag when pushing back up to my fork on #172, and like a n00b pulled again 😝  I was able to avoid this on #173, fortunately)
=> Zero byte unit fix, take 2

languages/pt-BR.js
=> default pt-BR currency is prefix, not postfix

.travis.yml
Not sure if there was a reason they were omitted (or if it just hasn't been updated yet). Let me know if you don't want these in.
=> Added two latest stable node versions to Travis build

numbro.js, tests/numbro/misc.js, tests/numbro/unformat.js
=> unformat: return undefined when value can't be parsed

numbro.d.ts, package.json
=> Add TypeScript declaration file

languages/en-AU.js, languages/en-NZ.js, tests/languages/en-AU.js, tests/languages/en-NZ.js
This PR adds the locales en-AU and en-NZ
=> Add locales en-AU and en-NZ

numbro.js
This PR adds the detection for Meteor (https://www.meteor.com)
Otherwise, numbro doesn't load the languages automatically
=> Add detection for Meteor

languages/index.js, languages/ro-RO.js, tests/languages/ro-RO.js
Continued work from https://github.com/foretagsplatsen/numbro/pull/161
=> Add Romanian locale

numbro.js, tests/numbro/format.js
=> Better input validation

languages/zh-HANT.js, tests/languages/zh-HANT.js
=> Added zh-HANT localization

languages/zh-HANS.js, tests/languages/zh-HANS.js
:warning:
this is based on top of #255
=> Added zh-HANS localization

languages/id.js, tests/languages/id.js
:warning:
based on top of #248
=> Added id localization

languages/nb.js, tests/languages/nb.js
:warning:
based on top of #248
=> Added nb localization

languages/ro.js, tests/languages/ro.js
:warning:
based on top of #248
=> Added ro localization

languages/sl.js, tests/languages/sl.js
:warning:
based on top of #248
=> Add sl localization

languages.html
Updates the docs with specifying the use of the function ```culture``` instead of ```language```
=> Update docs with culture instead of language

numbro.d.ts
Looking at existing language files, I think typings should be fixed like this.
=> Fix typings

numbro.d.ts
I forgot this one in my latest PR
=> "spaced" should be optional in typings

AUTHORS, CHANGELOG.md, src/formatting.js, tests/src/numbro-tests.js
=> Fixes #372

AUTHORS, CHANGELOG.md, src/unformatting.js, tests/src/unformatting-tests.js
=> Fixed unformat for non standard delimiters

AUTHORS, CHANGELOG.md, src/formatting.js, tests/src/formatting-tests.js
=> Fix formatCurrency when value > 0 and forceSign

AUTHORS, numbro.d.ts
Hey,
here we go again :).
Would you please merge this one. Would result in a cleaner history than fixing PR #468...
=> align typescript interface with validation properties

src/validating.js, tests/src/validating-tests.js
=> 0 is a valid input
